name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { os: ubuntu-latest, pip: ~/.cache/pip }
          - { os: macos-latest, pip: ~/Library/Caches/pip }
          - { os: windows-latest, pip: ~\AppData\Local\pip\Cache }
        python: ["3.7", "3.8", "3.9", "3.10"]
    name: "${{ matrix.config.os }} Python ${{ matrix.python }}"
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ matrix.config.pip }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: python -m unittest discover
